query GetAllEtfs(
	$locale: LanguageCodeFilterEnum!
	$search: String = ""
	$category: String = ""
	$pageSize: Int
	$skip: Int = 0
) {
	etfs(
		where: {
			language: $locale
			searchString: $search
			etfCategory: $category
			offsetPagination: { size: $pageSize, offset: $skip }
		}
	) {
		pageInfo {
			offsetPagination {
				hasMore
				total
			}
		}

		nodes {
			__typename
			id
			slug
			title
			uri

			language {
				code
			}

			cptEtfs {
				symbol
			}
		}
	}
}

query GetAllEtfsTags {
	etfTags {
		nodes {
			__typename
			id
			slug
			name
		}
	}
}

query GetAllEtfsLocales {
	etfs(first: 300) {
		nodes {
			__typename
			id
			slug
			language {
				code
				slug
			}
		}
	}
}

query GetAllEtfsForSitemap($pageSize: Int, $offset: Int, $locales: [LanguageCodeEnum!]!) {
	etfs(where: { offsetPagination: { size: $pageSize, offset: $offset }, languages: $locales }) {
		nodes {
			__typename
			id
			slug
			uri
			date
			language {
				code
				slug
			}
		}
	}
}
