query GetEtfsByCategory($categorySlug: String!, $locale: LanguageCodeFilterEnum!) {
	etfs(where: { etfCategory: $categorySlug, language: $locale }) {
		nodes {
			__typename
			id
			slug
			etfCategories {
				nodes {
					name
				}
			}
		}
	}
}

query GetEtfCategory($slug: ID!, $locale: LanguageCodeEnum!) {
	etfCategory(idType: SLUG, id: $slug) {
		translation(language: $locale) {
			name
			link
			uri

			seo {
				breadcrumbs {
					__typename
					text
					url
				}
				title
				metaDesc
				metaRobotsNofollow
				metaRobotsNoindex
				canonical
			}
		}
	}
}

query GetAllEtfCategoriesForSitemap($pageSize: Int, $offset: Int, $locales: [LanguageCodeEnum!]!) {
	etfCategories(where: { offsetPagination: { size: $pageSize, offset: $offset }, languages: $locales }) {
		nodes {
			__typename
			id
			slug
			uri
			language {
				code
				slug
			}
		}
	}
}
