query GetEtfBySlug($slug: ID!, $locale: LanguageCodeEnum!) {
	etf(idType: SLUG, id: $slug) {
		__typename
		translation(language: $locale) {
			id
			slug
			title
			uri
			date

			cptEtfs {
				symbol
				yield
				annualReportExpenseRatio
				tenYearReturn
			}

			cptEtfContent {
				subtitle
				content
			}

			etfCategories(first: 100) {
				nodes {
					id
					name
					uri
					link
					slug
				}
			}

			seo {
				title
				metaDesc
				breadcrumbs {
					url
					text
				}
			}
		}
	}
}
