query GetHeader($locale: LanguageCodeFilterEnum!) {
	menuItems(where: { location: HEADER, parentDatabaseId: 0, language: $locale }, first: 50) {
		nodes {
			__typename
			id
			label
			parentId
			uri

			childItems {
				nodes {
					__typename
					id
					label
					uri
					parentId
				}
			}
		}
	}
}
